[project]
name = "server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi[standard]>=0.121.2",
    "httpx>=0.28.1",
    "jinja2>=3.1.6",
    "pdfkit>=1.0.0",
    "pycups>=2.0.4",
    "pyinstaller>=6.17.0",
    "pypdf>=6.4.0",
    "qrcode>=8.2",
    "reactivex>=4.1.0",
    "reportlab>=4.2.2",
    "ruff>=0.14.6",
    "uvicorn>=0.38.0",
    "websockets>=15.0.1",
]
